### Registrar un Nuevo Usuario
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email_usuario": "http123.user1@example.com",
    "nombre_usuario": "HTTP",
    "apellido_usuario": "User",
    "password": "httppassword"
}

### Iniciar Sesión y Obtener un Token
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email_usuario": "http123.user1@example.com",
    "password": "httppassword"
}

### Acceder a una Ruta Protegida
### Acceder a una Ruta Protegida
GET http://localhost:8000/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJodHRwMTIzLnVzZXIxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxMjQ5MDc4fQ.Zi5M8sqh7BjgxdppUHGVdXCYong-MXSg-JW9-at1lco
