### Register a test user (run once)
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email_usuario": "test1122@example.com",
  "nombre_usuario": "Test",
  "apellido_usuario": "User",
  "password": "testpassword"
}

### Get an authentication token
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email_usuario": "test1122@example.com",
  "password": "testpassword"
}
### @name login

### Create a new product
POST http://127.0.0.1:8000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0MTEyMkBleGFtcGxlLmNvbSIsImV4cCI6MTc2MTMxNzE0MH0.lxtwQUnRc-ytkg1zQegzWtPTPbjC_FFJlbMrEKL9pCY

{
  "nombre_producto": "VODKOBICH ",
  "descripcion_producto": "PARA EL APPIO",
  "cantidad_producto": 1220,
  "precio_producto": 1200.00
}

### Get all products
GET http://127.0.0.1:8000/products
Content-Type: application/json

### Get product by ID
GET http://127.0.0.1:8000/products/4
Content-Type: application/json

### Update a product by ID
PUT http://127.0.0.1:8000/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0MTEyMkBleGFtcGxlLmNvbSIsImV4cCI6MTc2MTMxNzE0MH0.lxtwQUnRc-ytkg1zQegzWtPTPbjC_FFJlbMrEKL9pCY

{
  "nombre_producto": "Laptop Gamer Pro",
  "precio_producto": 1350.00
}

### Delete a product by ID
DELETE http://127.0.0.1:8000/products/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0MTEyMkBleGFtcGxlLmNvbSIsImV4cCI6MTc2MTMxNzE0MH0.lxtwQUnRc-ytkg1zQegzWtPTPbjC_FFJlbMrEKL9pCY
