"""primer migracion

Revision ID: 2d9732b8d5be
Revises: 
Create Date: 2025-09-11 10:22:56.658661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9732b8d5be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=True),
    sa.Column('descripcion_producto', sa.String(), nullable=True),
    sa.Column('cantidad_producto', sa.Integer(), nullable=True),
    sa.Column('precio_producto', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_cantidad_producto'), 'producto', ['cantidad_producto'], unique=False)
    op.create_index(op.f('ix_producto_descripcion_producto'), 'producto', ['descripcion_producto'], unique=False)
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.create_index(op.f('ix_producto_nombre_producto'), 'producto', ['nombre_producto'], unique=False)
    op.create_index(op.f('ix_producto_precio_producto'), 'producto', ['precio_producto'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=True),
    sa.Column('apellido_usuario', sa.String(), nullable=True),
    sa.Column('email_usuario', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_apellido_usuario'), 'usuario', ['apellido_usuario'], unique=False)
    op.create_index(op.f('ix_usuario_email_usuario'), 'usuario', ['email_usuario'], unique=True)
    op.create_index(op.f('ix_usuario_hashed_password'), 'usuario', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=False)
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compras')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_hashed_password'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_apellido_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_producto_precio_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_nombre_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_descripcion_producto'), table_name='producto')
    op.drop_index(op.f('ix_producto_cantidad_producto'), table_name='producto')
    op.drop_table('producto')
    # ### end Alembic commands ###
