"""Actualizacion de modelos y schemas para subir fotos

Revision ID: e32a9af44ebb
Revises: 2d9732b8d5be
Create Date: 2025-10-24 22:30:12.190825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32a9af44ebb'
down_revision: Union[str, Sequence[str], None] = '2d9732b8d5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'image_url')
    # ### end Alembic commands ###
